function mouse = getMouse(nDays, nTrials, mouse)

   % By-day curves for each threshold parameter
   thresh_max_curve = ...
      getCurve(mouse.meta.thresh.maxfin, ...
      mouse.meta.thresh.maxbeg, ...
      mouse.meta.thresh.tauday, ...
      nDays, 'down');
   
   thresh_min_curve = ...
      getCurve(mouse.meta.thresh.minfin, ...
      mouse.meta.thresh.minbeg, ...
      mouse.meta.thresh.tauday, ...
      nDays, 'down');
   
   thresh_tau_curve = ...
      getCurve(mouse.meta.thresh.taufin, ...
      mouse.meta.thresh.taubeg, ...
      mouse.meta.thresh.tauday, ...
      nDays, 'down');
   
   % By-day curves for each slope parameter
   slope_max_curve = ...
      getCurve(mouse.meta.slope.maxbeg, ...
      mouse.meta.slope.maxfin, ...
      mouse.meta.slope.tauday, ...
      nDays, 'up');
   
   slope_min_curve = ...
      getCurve(mouse.meta.slope.minbeg, ...
      mouse.meta.slope.minfin, ...
      mouse.meta.slope.tauday, ...
      nDays, 'up');
   
   slope_tau_curve = ...
      getCurve(mouse.meta.slope.taufin, ...
      mouse.meta.slope.taubeg, ...
      mouse.meta.slope.tauday, ...
      nDays, 'down');
   
   % Assemble into a "mouse"
   for d = 1:nDays
      % Threshold package for this day
      thresh.min = thresh_min_curve(d);
      thresh.max = thresh_max_curve(d);
      thresh.tau = thresh_tau_curve(d);
      thresh.curve = getCurve(thresh.min, thresh.max, thresh.tau, nTrials, 'down');
      
      % Slope package for this day
      slope.min = slope_min_curve(d);
      slope.max = slope_max_curve(d);
      slope.tau = slope_tau_curve(d);
      slope.curve = getCurve(slope.min, slope.max, slope.tau, nTrials, 'up');
      
      % Save the relevant info
      mouse.day(d).thresh = thresh;
      mouse.day(d).slope  = slope;
      mouse.day(d).lapse  = mouse.fixed.lapse;
      mouse.day(d).guess  = mouse.fixed.guess;
   end
end